import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from './utilities/header'
import Footer from './utilities/footer'
import ThemeProvider from "./utilities/ThemeProvider";
const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "SecuriScan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`bg-fixed bg-center bg-cover bg-gray-400 dark:bg-gray-900 text-black dark:text-white min-h-screen ${inter.className} antialiased`}
      >
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        >
          <Header />
            <main className="container mx-auto p-6">
              {children}
            </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
