import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from './utilities/header'
import Footer from './utilities/footer'
import ThemeProvider from "./utilities/ThemeProvider";
const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "SecuriScan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`bg-white dark:bg-black ${inter.className} antialiased`}
      >
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        >
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        
        </ThemeProvider>
      </body>
    </html>
  );
}
