"use client";

import React from "react";

export default function DependencyReport({ results }) {
  if (!results) {
    return <p className="text-gray-600">No scan results to display.</p>;
  }

  const scanId = `DEP-${new Date().getTime()}`;
  const scanDate = new Date().toLocaleString();
  const vulnerableCount = results.vulnerabilities?.length || 0;

  return (
    <div className="bg-white p-4 border rounded mt-4 text-black max-w-full">
      <h2 className="text-xl font-bold mb-2">Dependency Report</h2>

      {/* 1. Scan Summary */}
      <div className="mb-4">
        <h3 className="font-semibold">1. Scan Summary</h3>
        <ul className="ml-4 list-disc">
          <li><strong>Scan ID:</strong> {scanId}</li>
          <li><strong>Target URL:</strong> {results.url || "N/A"}</li>
          <li><strong>Scan Date:</strong> {scanDate}</li>
          <li><strong>Scanner Version:</strong> SecuriScan v1.0.0</li>
        </ul>
      </div>

      {/* 2. Detected Vulnerabilities */}
      <div className="mb-4">
        <h3 className="font-semibold">2. Detected Vulnerabilities</h3>
        {vulnerableCount > 0 ? (
          <p>
            Found <strong>{vulnerableCount}</strong> vulnerabilities in dependencies.
          </p>
        ) : (
          <p className="text-green-600">No vulnerable dependencies found.</p>
        )}

        {results.vulnerabilities && results.vulnerabilities.length > 0 && (
          <div className="overflow-x-auto mt-2">
            <table className="w-full border-collapse text-sm">
              <thead>
                <tr className="bg-gray-200 text-black">
                  <th className="border p-2">Issue</th>
                  <th className="border p-2">Evidence</th>
                  <th className="border p-2">Severity</th>
                </tr>
              </thead>
              <tbody>
                {results.vulnerabilities.map((vuln, idx) => (
                  <tr key={idx} className="hover:bg-gray-100">
                    <td className="border p-2">{vuln.issue}</td>
                    <td className="border p-2">{vuln.evidence}</td>
                    <td className={`border p-2 ${
                      vuln.severity === "High" || vuln.severity === "Critical"
                        ? "text-red-600"
                        : "text-yellow-600"
                    }`}>
                      {vuln.severity}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* 3. Detected Dependencies */}
      <div className="mb-4">
        <h3 className="font-semibold">3. Detected Dependencies</h3>
        {results.dependencies && results.dependencies.length > 0 ? (
          <ul className="list-disc ml-4 text-sm">
            {results.dependencies.map((dep, index) => (
              <li key={index} className={dep.library === "Unknown" ? "text-gray-500" : ""}>
                <strong>{dep.library}</strong> {dep.version || "unknown"} — {dep.status || "No status"} (
                <a
                  href={dep.source}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-indigo-500 underline"
                >
                  Source
                </a>)
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-gray-600">No third-party dependencies detected.</p>
        )}
      </div>

      {/* 4. Conclusion */}
      <div className="mb-4">
        <h3 className="font-semibold">4. Scan Conclusion</h3>
        {vulnerableCount > 0 ? (
          <p className="text-red-600">
            Vulnerable packages found. Please update or replace outdated libraries.
          </p>
        ) : (
          <p className="text-green-600">
            No known vulnerable dependencies detected. Regular scans are recommended.
          </p>
        )}
      </div>

      {/* 5. Footer */}
      <div className="mb-2">
        <h3 className="font-semibold">5. Report Generated By</h3>
        <p className="text-sm">
          Generated By: SecuriScan Automated Security Scanner <br />
          Report Format: PDF/HTML/Markdown <br />
          Contact: securiscan@gmail.com
        </p>
      </div>
    </div>
  );
}
