// components/LoggingMonitorReport.jsx
"use client";

import React from "react";

export default function LoggingMonitorReport({ results }) {
  if (!results) {
    return <p className="text-gray-600">No scan results to display.</p>;
  }

  const scanId = `LOG-${new Date().getTime()}`;
  const scanDate = new Date().toLocaleString();
  const vulnerableCount = results.vulnerabilities ? results.vulnerabilities.length : 0;

  return (
    <div className="bg-white p-4 border rounded mt-4 text-black max-w-full">
      <h2 className="text-xl font-bold mb-2">Logging & Monitoring Report</h2>

      {/* 1. Scan Summary */}
      <div className="mb-4">
        <h3 className="font-semibold">1. Scan Summary</h3>
        <ul className="ml-4 list-disc">
          <li><strong>Scan ID:</strong> {scanId}</li>
          <li><strong>Target URL:</strong> {results.url || "N/A"}</li>
          <li><strong>Scan Date:</strong> {scanDate}</li>
          <li><strong>Scanner Version:</strong> SecuriScan v1.0.0</li>
        </ul>
      </div>

      {/* 2. Detected Vulnerabilities */}
      <div className="mb-4">
        <h3 className="font-semibold">2. Detected Logging Issues</h3>
        {results.error ? (
          <p className="text-red-600">{results.error}</p>
        ) : vulnerableCount > 0 ? (
          <p>
            Found <strong>{vulnerableCount}</strong> logging or monitoring issues.
          </p>
        ) : (
          <p className="text-green-600">No logging or monitoring issues detected.</p>
        )}

        {results.vulnerabilities && results.vulnerabilities.length > 0 && (
          <div className="overflow-x-auto mt-2">
            <table className="w-full border-collapse text-sm">
              <thead>
                <tr className="bg-gray-200 text-black">
                  <th className="border p-2">Issue</th>
                  <th className="border p-2">Evidence</th>
                  <th className="border p-2">Severity</th>
                </tr>
              </thead>
              <tbody>
                {results.vulnerabilities.map((vuln, idx) => (
                  <tr key={idx} className="hover:bg-gray-100">
                    <td className="border p-2">{vuln.issue}</td>
                    <td className="border p-2">{vuln.evidence || "N/A"}</td>
                    <td
                      className={`border p-2 ${
                        vuln.severity === "High" ? "text-red-600" : "text-yellow-600"
                      }`}
                    >
                      {vuln.severity || "Medium"}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* 3. Additional Details */}
      <div className="mb-4">
        <h3 className="font-semibold">3. Additional Observations</h3>
        {results.response_time ? (
          <p>
            Response Time: {results.response_time} ms (
            {results.response_time > 1000 ? (
              <span className="text-red-600">Slow - potential logging delay</span>
            ) : (
              "Acceptable"
            )})
          </p>
        ) : (
          <p className="text-gray-600">No response time data available.</p>
        )}
        {results.headers ? (
          <div>
            <p>Security Headers Present: {Object.keys(results.headers).length}</p>
            <ul className="list-disc ml-4 text-sm">
              {Object.entries(results.headers).map(([key, value], idx) => (
                <li key={idx}>
                  {key}: {value}
                </li>
              ))}
            </ul>
          </div>
        ) : (
          <p className="text-gray-600">No security headers detected.</p>
        )}
      </div>

      {/* 4. Conclusion */}
      <div className="mb-4">
        <h3 className="font-semibold">4. Scan Conclusion</h3>
        {results.error ? (
          <p className="text-red-600">Scan failed: {results.error}</p>
        ) : vulnerableCount > 0 ? (
          <p className="text-red-600">
            Detected <strong>{vulnerableCount}</strong> logging issues. Enhance logging and monitoring practices.
          </p>
        ) : (
          <p className="text-green-600">
            Logging and monitoring appear adequate based on this scan. Regular checks recommended.
          </p>
        )}
      </div>

      {/* 5. Footer */}
      <div className="mb-2">
        <h3 className="font-semibold">5. Report Generated By</h3>
        <p className="text-sm">
          Generated By: SecuriScan Automated Security Scanner <br />
          Report Format: PDF/HTML/Markdown <br />
          Contact: securiscan@gmail.com
        </p>
      </div>
    </div>
  );
}