 "use client";

import React from "react";

export default function SsrfReport({ results }) {
  if (!results) {
    return <p className="text-gray-300">No scan results to display.</p>; // Changed to match parent text color
  }

  const scanId = `SSRF-${new Date().getTime()}`;
  const scanDate = new Date().toLocaleString();
  const vulnerableCount = results.vulnerabilities ? results.vulnerabilities.length : 0;

  return (
    <div className="bg-gray-700 p-4 rounded-lg text-white max-w-full"> {/* Adjusted bg to match parent */}
      <h2 className="text-xl font-bold mb-2">SecuriScan SSRF Report</h2>

      {/* 1. Scan Summary */}
      <div className="mb-4">
        <h3 className="font-semibold">1. Scan Summary</h3>
        <ul className="ml-4 list-disc">
          <li><strong>Scan ID:</strong> {scanId}</li>
          <li><strong>Target URL:</strong> {results.url || "N/A"}</li>
          <li><strong>Scan Date:</strong> {scanDate}</li>
          <li><strong>Scanner Version:</strong> SecuriScan v1.2.0</li>
        </ul>
      </div>

      {/* 2. Detected SSRF Vulnerabilities */}
      <div className="mb-4">
        <h3 className="font-semibold">2. Detected SSRF Vulnerabilities</h3>
        {results.error ? (
          <p className="text-red-400">{results.error}</p>
        ) : vulnerableCount > 0 ? (
          <p>
            Found <strong>{vulnerableCount}</strong> potential SSRF vulnerability(s).
          </p>
        ) : (
          <p className="text-green-400">No SSRF vulnerabilities detected.</p>
        )}

        {results.vulnerabilities && results.vulnerabilities.length > 0 && (
          <div className="overflow-x-auto mt-2">
            <table className="w-full border-collapse text-sm">
              <thead>
                <tr className="bg-gray-600 text-white">
                  <th className="border p-2">Issue</th>
                  <th className="border p-2">Evidence</th>
                  <th className="border p-2">Severity</th>
                </tr>
              </thead>
              <tbody>
                {results.vulnerabilities.map((vuln, idx) => (
                  <tr key={idx} className="hover:bg-gray-600">
                    <td className="border p-2">{vuln.issue}</td>
                    <td className="border p-2">{vuln.evidence || "N/A"}</td>
                    <td
                      className={`border p-2 ${
                        vuln.severity === "Critical" || vuln.severity === "High"
                          ? "text-red-400"
                          : "text-yellow-400"
                      }`}
                    >
                      {vuln.severity || "Medium"}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* 3. Additional Observations */}
      <div className="mb-4">
        <h3 className="font-semibold">3. Additional Observations</h3>
        {results.suspicious_endpoints && results.suspicious_endpoints.length > 0 ? (
          <div className="text-red-400">
            <p>Detected <strong>{results.suspicious_endpoints.length}</strong> suspicious endpoint(s):</p>
            <ul className="list-disc pl-5">
              {results.suspicious_endpoints.map((endpoint, idx) => (
                <li key={idx}>{endpoint}</li>
              ))}
            </ul>
          </div>
        ) : (
          <p className="text-gray-300">No suspicious endpoints detected.</p>
        )}
      </div>

      {/* 4. Conclusion */}
      <div className="mb-4">
        <h3 className="font-semibold">4. Scan Conclusion</h3>
        {results.error ? (
          <p className="text-red-400">Scan failed: {results.error}</p>
        ) : vulnerableCount > 0 || (results.suspicious_endpoints && results.suspicious_endpoints.length > 0) ? (
          <p className="text-red-400">
            Detected <strong>{vulnerableCount + (results.suspicious_endpoints ? results.suspicious_endpoints.length : 0)}</strong> issue(s).
            Immediate remediation recommended to prevent SSRF attacks.
          </p>
        ) : (
          <p className="text-green-400">
            No SSRF vulnerabilities found. Regular scans advised.
          </p>
        )}
      </div>

      {/* 5. Footer */}
      <div className="mb-2">
        <h3 className="font-semibold">5. Report Generated By</h3>
        <p className="text-sm">
          Generated By: SecuriScan Automated Security Scanner <br />
          Report Format: PDF/HTML/Markdown <br />
          Contact: security@example.com
        </p>
      </div>
    </div>
  );
}